"""empty message

Revision ID: ce862b08ab83
Revises: c9ccde374cc4
Create Date: 2021-04-28 17:06:03.951725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce862b08ab83'
down_revision = 'c9ccde374cc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('follows', 'followerId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('follows', 'userId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('follows', 'created_at')
    op.drop_column('follows', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('follows', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('follows', 'userId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('follows', 'followerId',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
