"""empty message

Revision ID: cffb73748436
Revises: 3d8ebe1d190b
Create Date: 2021-07-07 16:54:02.603538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cffb73748436'
down_revision = '3d8ebe1d190b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_postId_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['postId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_postId_fkey', 'comments', 'posts', ['postId'], ['id'])
    # ### end Alembic commands ###
