"""empty message

Revision ID: e94d89054bc5
Revises: cffb73748436
Create Date: 2021-07-07 16:55:16.655081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e94d89054bc5'
down_revision = 'cffb73748436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('likes_postId_fkey', 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'posts', ['postId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key('likes_postId_fkey', 'likes', 'posts', ['postId'], ['id'])
    # ### end Alembic commands ###
